version: "3"
services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password@123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - 5672:5672
      - 15672:15672

  # publisher:
  #   image: demo/publisher
  #   environment: 
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:80
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.publisher
  #   ports:
  #    - 4000:80
  # consumer:
  #   image: demo/consumer
  #   environment: 
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.consumer1
